[WIP] Ast parser
Washi1337/Echo pull request #48
Opened 2020-08-04 18:45 UTC by zsr2531

2020-08-12 19:00 UTC, Washi1337 commented
Linked to #50

2020-08-15 10:43 UTC, zsr2531 commented
Linked to #51

2020-10-06 14:02 UTC, Washi1337 requested changes

2020-10-06 14:02 UTC, Washi1337 commented on src/Core/Echo.Ast/InstructionExpression.cs
> +        /// <summary>
Add constructor for expressions without arguments, and a `params Expression<TInstruction>[]` for consistency and readability.

2020-10-06 14:29 UTC, zsr2531 commented on src/Core/Echo.ControlFlow/Serialization/Dot/ControlFlowNodeAdorner.cs
> -            : this(DefaultInstructionFormatter<TInstruction>.Instance) { }
No idea, I forgot to be honest :D

2020-10-06 15:56 UTC, Washi1337 approved these changes

2020-10-06 15:58 UTC, merged