Integer division and remainder algorithms #19
Washi1337/Echo pull request #74
Opened 2020-10-28 16:58 UTC by mirec12590

I created dividing algorithm to count divide only and I added tests to test division.

Dividing is count as substracting.

2020-10-28 18:35 UTC, zsr2531 requested changes
Firstly; Overall, nice job! Apart from the minor style issues, you should override the `Divide` method in `Integer8Value`, `Integer16Value`, `Integer32Value` and `Integer64Value`. And check if both sides are fully known and are the same type, then you can just divide normally; `num1 / num2`. ([An example of what you should do](https://github.com/Washi1337/Echo/blob/2a1873b56184a7a24675d773c6188b8a045403cc/src/Core/Echo.Concrete/Values/ValueType/Integer32Value.cs#L230))

Secondly; Will you also implement a `Remainder` method?

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +            var multipliedByOne = (IntegerValue)Copy();
There should be a space following a cast.
ie. `(int) 0.0f`.

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +            var multipliedByUnknown = (IntegerValue)Copy();
There should be a space following a cast.
ie. `(int) 0.0f`.

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +                throw new ArgumentException("Divisor is zero and dividing by zero is not allowed.");
You can remove the braces here since the body of the `if` is only 1 line.
```csharp
if (expr)
	stmt;
```

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +            var firstNum = (IntegerValue)Copy();
There should be a space following a cast.
ie. `(int) 0.0f`.

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +            var secondNum = (IntegerValue)other.Copy();
There should be a space following a cast.
ie. `(int) 0.0f`.

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +            var oneNum = (IntegerValue)Copy();
There should be a space following a cast.
ie. `(int) 0.0f`.

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +            var firstResult = (IntegerValue)Copy();
There should be a space following a cast.
ie. `(int) 0.0f`.

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +                    firstNum.SetBit(i, Trilean.False);
You can remove the braces here since the body of the `if` is only 1 line.
```csharp
if (expr)
	stmt;
```

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +                    secondNum.SetBit(i, Trilean.True);
You can remove the braces here since the body of the `if` is only 1 line.
```csharp
if (expr)
	stmt;
```

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +            firstNum = (IntegerValue)Copy();
There should be a space following a cast.
ie. `(int) 0.0f`.

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +            secondNum = (IntegerValue)other.Copy();
There should be a space following a cast.
ie. `(int) 0.0f`.

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +            var secondResult = (IntegerValue)Copy();
There should be a space following a cast.
ie. `(int) 0.0f`.

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +                    firstNum.SetBit(i, Trilean.True);
You can remove the braces here since the body of the `if` is only 1 line.
```csharp
if (expr)
	stmt;
```

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +                    secondNum.SetBit(i, Trilean.False);
You can remove the braces here since the body of the `if` is only 1 line.
```csharp
if (expr)
	stmt;
```

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +                secondNum.Add(oneNum);
You can remove the braces here since the body of the `if` is only 1 line.
```csharp
if (expr)
	stmt;
```

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +            var result = (IntegerValue)Copy();
Prefer to use the ternary operator here.
ie. `cond ? expr1 : expr2;`

2020-10-28 18:35 UTC, zsr2531 commented on src/Core/Echo.Concrete/Values/ValueType/IntegerValue.cs
> +                    if (result.GetBit(i) == Trilean.False && !isZeroBit)
Invert if, so `continue` can be ommitted.

2020-10-28 18:36 UTC, zsr2531 commented
Also, are you doing Hacktoberfest? If so, I can add the label to this PR.

2020-10-29 06:32 UTC, mirec12590 commented
Hi, I haven't implemented remainder yet. But I will look at this after this successful merge.

2020-10-29 07:29 UTC, zsr2531 commented
Then you should reflect that in the PR's title. Something like `Add division for integer values` would be much better. And also, after you make the changes requested, I'll merge this PR :smile: @mirec12590 .

2020-10-29 08:14 UTC, zsr2531 approved these changes
Nicely done! Would you like me to add the hacktoberfest label?

2020-10-29 08:21 UTC, mirec12590 commented
You can add but it is not needed 😸

2020-10-29 08:21 UTC, zsr2531 commented
Alright, I'll just merge this then. :smile:

2020-10-29 08:21 UTC, merged